version: '3.8'

services:
  db:
    image: postgres:15
    container_name: too-doos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: too_doos
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: too-doos-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/too_doos?schema=public
    command: sh -c "npx prisma migrate deploy && node src/index.js"

volumes:
  db-data:
